In [1]:
# https://blog.naver.com/ostin1038/222110587918

In [2]:
import pandas as pd
import numpy as np

In [6]:
D = pd.read_csv('public_imbclty_cnter.csv',sep='\t')

In [7]:
D.shape

(285, 7)

In [8]:
D.head()

,cnterNm,rdnmadr,bildngAr,doctrCo,nurseCo,scrcsCo,etcHnfSttus
0,의령군보건소 치매안심센터,경상남도 의령군 의병로 8길 16-1,838.18,1,10,1,3
1,거제시 치매안심센터,경상남도 거제시 거제중앙로 13길 25,959.22,1,18,2,1
2,양평군치매안심센터,경기도 양평군 양평읍 중앙로111번길 34,251.00,1,5,5,7
3,금산군치매안심센터,충청남도 금산군 금산읍 비범1길5,419.00,2,8,5,2
4,부여군치매안심센터,충청남도 부여군 부여읍 성왕로 205,500.00,1,10,3,2

In [9]:
"""
전처리

건축물면적 변수 결측치 제거(최종 행 수 236개)

소재지도로명주소를 통해 광역시와 지방행정구역(도) 정보 변수를 추가하라

이때 전라, 충청, 경상은 하나로 통합한다.

(ex:전라남도 -> 전라도, 충청남도 -> 충청도, 경상남도 -> 경상도)
"""

'\n전처리\n\n건축물면적 변수 결측치 제거(최종 행 수 236개)\n\n소재지도로명주소를 통해 광역시와 지방행정구역(도) 정보 변수를 추가하라\n\n이때 전라, 충청, 경상은 하나로 통합한다.\n\n(ex:전라남도 -> 전라도, 충청남도 -> 충청도, 경상남도 -> 경상도)\n'

In [12]:
D.dropna(subset=['bildngAr'], axis=0)

,cnterNm,rdnmadr,bildngAr,doctrCo,nurseCo,scrcsCo,etcHnfSttus
0,의령군보건소 치매안심센터,경상남도 의령군 의병로 8길 16-1,838.18,1,10,1,3
1,거제시 치매안심센터,경상남도 거제시 거제중앙로 13길 25,959.22,1,18,2,1
2,양평군치매안심센터,경기도 양평군 양평읍 중앙로111번길 34,251.00,1,5,5,7
3,금산군치매안심센터,충청남도 금산군 금산읍 비범1길5,419.00,2,8,5,2
4,부여군치매안심센터,충청남도 부여군 부여읍 성왕로 205,500.00,1,10,3,2
5,서천군치매안심센터,충청남도 서천군 서천읍 사곡길 20-2,906.00,2,10,2,3
6,청양군치매안심센터,충청남도 청양군 청양읍 칠갑산로 7길54,995.00,1,6,2,2
7,홍성군매안심센터,충청남도 홍성군 홍성읍 문화로 106,498.00,1,18,2,7
8,예산군치매안심센터,충청남도 예산군 예산읍 군청로22/ 예산군보건소 5층,427.55,2,12,1,4
9,태안군치매안심센터,충청남도 태안군 태안읍 서해로1952-16,330.00,1,11,2,3
11,영통구치매안심센터,경기도 수원시 영통구 영통로 396/ 영통구보건소 5층,440.78,0,11,4,3
12,장안구치매안심센터,경기도 수원시 장안구 송원로 101/ (조원동),482.00,0,13,3,2
13,권선구치매안심센터,경기도 수원시 권선구 호매실로 22-50(탑동),498.00,0,11,3,3
14,팔달구치매안심센터,경기도 수원시 팔달구 팔달산로 6 (교동),388.00,0,13,3,2
15,부산진구치매안심센터,부산광역시 부산진구 새싹로253,548.48,1,12,6,2
16,파주시 치매안심센터,경기도 파주시 조리읍 봉천로 68(건강증진센터 3층),356.42,1,9,4,5
17,안성시 치매안심센터,경기도 안성시 강변로 74번길 18,792.07,0,7,5,9
18,연제구치매상담센터,부산광역시 연제구 거제시장로22번길 70(거제동),469.63,0,11,2,5
19,인제군치매안심센터,강원도 인제군 인제읍 인제로140번길 34,719.30,1,4,4,4
20,경주시 치매상담센터,경상북도 경주시 봉황로 178,633.00,0,16,2,6
22,부안군 치매센터,전라북도 부안군 부안읍 오리정로 124,214.98,0,7,3,2
23,태안군치매안심센터,충청남도 태안군 태안읍 서해로 1952-16,330.00,1,4,2,1
25,서산시치매안심센터,충청남도 서산시 호수공원 6로 6,350.00,1,6,4,5
26,논산시치매안심센터,충청남도 논산시 논산대로 382,730.27,1,14,2,4
27,계룡시치매안심센터,충청남도 계룡시 장안로 54,396.00,1,3,1,4
28,당진시치매안심센터,충청남도 당진시 서부로 56,600.00,1,10,4,4
29,마포구치매지원센터,서울특별시 마포구 대흥로 122,624.00,1,7,3,2
30,영월군 치매안심센터,강원도 영월군 영월읍 하송로 46-43,462.00,1,5,2,2
31,화천군정신건강증진센터,강원도 화천군 화천읍 강변로 111,86.92,0,2,0,0
33,경기도 송탄보건소,경기도 평택시 경기대로 1366,778.00,0,6,0,0
...,...,...,...,...,...,...,...
252,광양시 치매안심센터,전라남도 광양시 광양읍 호북길 13-3,593.00,1,6,1,0
254,서구 치매안심센터,광주광역시 서구 운천로172번길 32(쌍촌동),217.00,0,11,1,3
255,안산시상록수보건소 치매안심센터,경기도 안산시 상록구 차돌배기로1길 5,430.00,4,15,3,2
256,김천시 보건소,경상북도 김천시 시청1길 221(신음동/ 김천시보건소),2147.61,0,2,0,0
257,담양군치매안심센터,전라남도 담양군 담양읍 완동길 10-5,613.81,1,7,3,5
258,세종특별자치시 치매안심센터(조치원),세종특별자치시 조치원읍 수원지1길 16,439.00,0,4,2,2
259,세종특별자치시 치매안심센터(어진동),세종특별자치시 다솜1로 31,439.00,0,4,2,1
260,세종특별자치시광역치매센터,세종특별자치시 조치원읍 수원지1길 16,439.00,1,2,2,2
261,만안치매안심센터,경기도 안양시 만안구 문예로 48 (6층),406.80,1,7,1,2
262,산청군 치매안심센터,경상남도 산청군 산청읍 중앙로97,881.52,0,4,0,2
263,증평군치매안신셈터,충청북도 증평군 증평읍 보건복지로 64-1,117.70,0,3,3,2
264,동작구치매안심센터,서울특별시 동작구 남부순환로 2025,988.20,2,9,3,7
265,대구남구치매안심센터,대구광역시 남구 영선길 34,215.90,0,8,3,5
267,울주치매안심센터,울산광역시 울주군 웅촌면 은현작동로 49,300.78,1,10,2,4
268,보령시치매안심센터,충청남도 보령시 대천로 113,490.19,0,4,3,2
269,금천구치매안심센터,서울특별시 금천구 시흥대로123길 11,748.10,1,8,3,4
270,은평구치매안심센터,서울특별시 은평구 연서로34길 11,520.78,1,9,3,4
271,원주시치매상담센터,강원도 원주시 원일로 139 (건강문화센터 3층),5.50,0,10,0,4
272,부산광역시광역치매센터,부산광역시 서구 대신공원로26 센터동 10층,649.81,1,2,2,4
273,양주시 치매안심센터,경기도 양주시 화합로1426번길 90,595.00,2,5,1,4
274,중구치매안심센터,대전광역시 중구 중앙로 100,647.00,1,4,1,4
275,서구치매안심센터,대전광역시 서구 둔산서로 100,711.00,1,11,4,4
276,유성구치매안심센터,대전광역시 유성구 유성대로730번길 51,457.00,1,7,3,4
277,대덕구치매안심센터,대전광역시 대덕구 동춘당로 187,487.00,1,8,1,5
278,공주시치매안심센터,충청남도 공주시 봉황로 123 공주시보건소 1층,210.00,2,10,2,5
279,고흥군 치매안심센터,전라남도 고흥군 고흥읍 등암3길 5,330.00,0,4,1,2
280,함양군 치매안심센터,경상남도 함양군 함양읍 한들로 141,398.00,1,6,1,2
281,마산보건소 치매안심센터,경상남도 창원시 마산합포구 월영동북로15,662.00,1,7,1,1
282,진해보건소 서부보건지소 치매안심센터,경상남도 창원시 진해구 중원동로 62,40.00,0,4,2,1
284,춘천시 치매안심센터,강원도 춘천시 스무숲길 4-46,2347.61,2,16,2,2

In [13]:
D = D.dropna(subset=['bildngAr'], axis=0)

In [22]:
search = ['전라남도','전라북도','경상남도','경상북도','충청남도','충청북도']
substitute = ['전라도','전라도','경상도','경상도','충청도','충청도']
D.rdnmadr.apply(lambda x : x.split(' ')[0]).replace(to_replace=search, value=substitute).value_counts()

충청도        40
경기도        40
경상도        30
전라도        26
서울특별시      23
부산광역시      14
강원도        13
인천광역시      12
울산광역시      10
대전광역시       8
대구광역시       7
제주특별자치도     6
광주광역시       4
세종특별자치시     3
Name: rdnmadr, dtype: int64

In [23]:
D['region'] = D.rdnmadr.apply(lambda x : x.split(' ')[0]).replace(to_replace=search, value=substitute).copy()

In [24]:
D.head()

,cnterNm,rdnmadr,bildngAr,doctrCo,nurseCo,scrcsCo,etcHnfSttus,region
0,의령군보건소 치매안심센터,경상남도 의령군 의병로 8길 16-1,838.18,1,10,1,3,경상도
1,거제시 치매안심센터,경상남도 거제시 거제중앙로 13길 25,959.22,1,18,2,1,경상도
2,양평군치매안심센터,경기도 양평군 양평읍 중앙로111번길 34,251.00,1,5,5,7,경기도
3,금산군치매안심센터,충청남도 금산군 금산읍 비범1길5,419.00,2,8,5,2,충청도
4,부여군치매안심센터,충청남도 부여군 부여읍 성왕로 205,500.00,1,10,3,2,충청도

In [25]:
D.shape

(236, 8)

In [26]:
# Q1
"""
Q1: 센터별 전체 임직원 수 변수(의사인원 + 간호사인원 + 사회복지사인원 + 

      기타  인원)를 추가하고 건축물면적(㎡)당 인원수를 확인하라

      이때 건축물면적(㎡)당 인원수 아웃라이어 갯수는?(tukey 방식 활용) 
"""

'\nQ1: 센터별 전체 임직원 수 변수(의사인원 + 간호사인원 + 사회복지사인원 + \n\n      기타  인원)를 추가하고 건축물면적(㎡)당 인원수를 확인하라\n\n      이때 건축물면적(㎡)당 인원수 아웃라이어 갯수는?(tukey 방식 활용) \n'

In [27]:
D['allCo'] = D['doctrCo'] +  D['nurseCo'] + D['scrcsCo'] + D['etcHnfSttus']
D['dens'] =  D['allCo']/D['bildngAr']
D.head()

,cnterNm,rdnmadr,bildngAr,doctrCo,nurseCo,scrcsCo,etcHnfSttus,region,allCo,dens
0,의령군보건소 치매안심센터,경상남도 의령군 의병로 8길 16-1,838.18,1,10,1,3,경상도,15,0.017896
1,거제시 치매안심센터,경상남도 거제시 거제중앙로 13길 25,959.22,1,18,2,1,경상도,22,0.022935
2,양평군치매안심센터,경기도 양평군 양평읍 중앙로111번길 34,251.00,1,5,5,7,경기도,18,0.071713
3,금산군치매안심센터,충청남도 금산군 금산읍 비범1길5,419.00,2,8,5,2,충청도,17,0.040573
4,부여군치매안심센터,충청남도 부여군 부여읍 성왕로 205,500.00,1,10,3,2,충청도,16,0.032000

In [34]:
D.dens.describe()

count    236.000000
mean       0.052504
std        0.171273
min        0.000931
25%        0.021155
50%        0.030802
75%        0.042999
max        2.545455
Name: dens, dtype: float64

In [45]:
Q1 = D.dens.describe()['25%']
Q3 = D.dens.describe()['75%']
IQR = Q3 - Q1
lb = Q1 - 1.5*IQR
hb = Q3 + 1.5*IQR
Q1, Q3, IRQ, lb, hb

(0.021154888574543534,
 0.042998858083588797,
 0.021843969509045262,
 -0.011611065689024355,
 0.07576481234715668)

In [46]:
Q1 = np.percentile(D.dens, 25)
Q3 = np.percentile(D.dens, 75)
IQR = Q3 - Q1
lb = Q1 - 1.5*IQR
hb = Q3 + 1.5*IQR
Q1, Q3, IQR, lb, hb

(0.021154888574543534,
 0.042998858083588797,
 0.021843969509045262,
 -0.011611065689024355,
 0.07576481234715668)

In [53]:
D[(D.dens < lb)|(D.dens > hb)].shape

(17, 10)

In [54]:
# Q2
"""
Q2: Q1에서 확인한 아웃라이어를 제거한 후 Q2, Q3 진행 

     도별 Q1에서 구한 건축물면적당 인원수 평균이 차이나는지 확인하고자 한다. 

     경기도, 충청도, 전라도, 경상도, 강원도 5개 도의 건축물면적당 인원수 평균이 

     통계적으로 유의미하게 차이가 난다고 볼 수 있는가?

     (등분산, 정규성을 가진다 가정하고 일원산분석 ANOVA 검정을 수행한다)

 

     차이가 있으면 Y, 없으면 N로 표시하고 

     차이가 있을 시 검정통계량을 소수점 둘째자리(셋째자리 버림)까지 표시하여라
"""

'\nQ2: Q1에서 확인한 아웃라이어를 제거한 후 Q2, Q3 진행 \n\n     도별 Q1에서 구한 건축물면적당 인원수 평균이 차이나는지 확인하고자 한다. \n\n     경기도, 충청도, 전라도, 경상도, 강원도 5개 도의 건축물면적당 인원수 평균이 \n\n     통계적으로 유의미하게 차이가 난다고 볼 수 있는가?\n\n     (등분산, 정규성을 가진다 가정하고 일원산분석 ANOVA 검정을 수행한다)\n\n \n\n     차이가 있으면 Y, 없으면 N로 표시하고 \n\n     차이가 있을 시 검정통계량을 소수점 둘째자리(셋째자리 버림)까지 표시하여라\n'

In [55]:
D2 = D[(D.dens > lb)&(D.dens < hb)]
D2.shape

(219, 10)

In [60]:
D[D.region=='경기도'].shape, D[D.region=='충청도'].shape, D[D.region=='전라도'].shape, D[D.region=='경상도'].shape, D[D.region=='강원도'].shape,

((40, 10), (40, 10), (26, 10), (30, 10), (13, 10))

In [56]:
import scipy.stats as stats

In [62]:
stats.f_oneway(D[D.region=='경기도'].dens, 
               D[D.region=='충청도'].dens, 
               D[D.region=='전라도'].dens, 
               D[D.region=='경상도'].dens, 
               D[D.region=='강원도'].dens)

F_onewayResult(statistic=1.9600411128879283, pvalue=0.10374978573703239)

In [63]:
# Q3
"""
Q3: 건축물면적, 총 임직원수, 의사수 3개 변수를 독립변수로 

     간호사수를 종속변수로 하여 다중 회귀분석을 실시하고자 한다.

     이때 전체 219개 센터를 대상으로 Split 함수를 사용하여 Train set과 

     Test set을 7:3으로 분할(seed=123)한 데이터로 모델을 설정하고자 한다.      

    TrainSet바탕의 모델을 TestSet으로 수행했을 때  간호사 인원수를 10명 이상 예측한 센터는 모두 몇개인가?
"""

'\nQ3: 건축물면적, 총 임직원수, 의사수 3개 변수를 독립변수로 \n\n     간호사수를 종속변수로 하여 다중 회귀분석을 실시하고자 한다.\n\n     이때 전체 219개 센터를 대상으로 Split 함수를 사용하여 Train set과 \n\n     Test set을 7:3으로 분할(seed=123)한 데이터로 모델을 설정하고자 한다.      \n\n    TrainSet바탕의 모델을 TestSet으로 수행했을 때  간호사 인원수를 10명 이상 예측한 센터는 모두 몇개인가?\n'

In [111]:
D2.head()[['bildngAr', 'allCo', 'doctrCo', 'nurseCo']]

   bildngAr  allCo  doctrCo  nurseCo
0    838.18     15        1       10
1    959.22     22        1       18
2    251.00     18        1        5
3    419.00     17        2        8
4    500.00     16        1       10

In [89]:
from  sklearn.model_selection import train_test_split

In [112]:
train, test = train_test_split(D2[['allCo', 'doctrCo','bildngAr', 'nurseCo']].values, test_size=0.3, random_state=123)

In [113]:
train.shape, test.shape

((153, 4), (66, 4))

In [114]:
train_X = train[:, 0:3]
train_y = train[:,3]
test_X = test[:, 0:3]
test_y = test[:, 3]

In [105]:
from sklearn.linear_model import LinearRegression

In [115]:
lin = LinearRegression()

In [116]:
lin.fit(train_X, train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [117]:
pred = lin.predict(test_X)

In [118]:
pred

array([ 8.90572824,  8.89958605, 12.17506947,  8.87171729, 10.25272461,
        5.61745906,  5.64100003,  4.97682572,  5.60493508,  6.58116274,
        5.04129477, 13.84536588, 10.95592279,  9.84231227,  6.56190533,
        8.61275378, 13.49878442,  7.91351491,  8.66413366,  5.56073661,
       11.17956261,  7.42532674,  5.54257076,  4.89701949,  8.45119042,
        8.27364655,  6.15047195,  8.3909634 ,  1.80325507,  3.78643571,
        7.17194517,  3.66632275,  5.98488281,  5.11374106,  6.84974989,
       11.4206351 ,  3.15303342,  7.88318054, 10.2145693 ,  8.1651708 ,
        4.37070611,  6.77912833, 10.24141187,  3.82225836,  7.57068302,
        4.78208494,  7.77204766,  5.78843365, 10.81721664, 10.8507145 ,
       11.98874266, 11.36917437,  2.41651185,  8.31603197,  8.33946359,
        5.39166623, 11.39224132,  4.16147472, 11.52249486,  4.36942976,
        4.29357252,  7.17542775,  6.02453453,  9.64509041,  3.74148971,
        8.00157726])

In [122]:
pred[pred>10]

array([12.17506947, 10.25272461, 13.84536588, 10.95592279, 13.49878442,
       11.17956261, 11.4206351 , 10.2145693 , 10.24141187, 10.81721664,
       10.8507145 , 11.98874266, 11.36917437, 11.39224132, 11.52249486])

In [123]:
test_y[test_y>10]

array([12., 11., 16., 11., 15., 15., 14., 11., 13., 11., 11., 14., 11.,
       11., 14.])

In [125]:
pd.DataFrame(data={'predict':pred, 'true': test_y})

      predict  true
0    8.905728  10.0
1    8.899586   8.0
2   12.175069  12.0
3    8.871717  11.0
4   10.252725   9.0
5    5.617459   5.0
6    5.641000   7.0
7    4.976826   5.0
8    5.604935   5.0
9    6.581163   8.0
10   5.041295   4.0
11  13.845366  16.0
12  10.955923  11.0
13   9.842312   7.0
14   6.561905   7.0
15   8.612754   8.0
16  13.498784  15.0
17   7.913515   6.0
18   8.664134   8.0
19   5.560737   4.0
20  11.179563  15.0
21   7.425327   9.0
22   5.542571   5.0
23   4.897019   6.0
24   8.451190  10.0
25   8.273647   7.0
26   6.150472   8.0
27   8.390963  10.0
28   1.803255   1.0
29   3.786436   4.0
..        ...   ...
36   3.153033   2.0
37   7.883181   8.0
38  10.214569  11.0
39   8.165171   8.0
40   4.370706   4.0
41   6.779128   7.0
42  10.241412  13.0
43   3.822258   4.0
44   7.570683   9.0
45   4.782085   4.0
46   7.772048  10.0
47   5.788434   6.0
48  10.817217   8.0
49  10.850714  11.0
50  11.988743  11.0
51  11.369174  14.0
52   2.416512   2.0
53   8.316032  11.0
54   8.339464   8.0
55   5.391666   5.0
56  11.392241  11.0
57   4.161475   3.0
58  11.522495  14.0
59   4.369430   3.0
60   4.293573   3.0
61   7.175428  10.0
62   6.024535   4.0
63   9.645090  10.0
64   3.741490   6.0
65   8.001577   7.0

[66 rows x 2 columns]

In [130]:
lin.score(train_X, train_y) # 결정계수

0.6631874645720279

In [131]:
lin.coef_ # 회귀계수

array([ 0.5842704 , -0.63340229,  0.0006512 ])

In [132]:
lin.intercept_ # bias

-0.5893350540935636