In [1]:
# https://blog.naver.com/ostin1038/222116828334

In [ ]:
# 나오기 어렵다 fp growth vs

In [2]:
_ = """

1. 지지도(Support)
   전체 거래 항목 중 A, B를 동시에 포함하여 거래하는 비율

   지지도 s(A→B) = P(A∩B)  :  A와 B가 동시에 포함된 거래 수 / 전체 거래 수
   
   : 거래 빈도

2. 신뢰도(Confidence)

   상품 A를 포함하는 거래 중 A와 B가 동시에 거래되는 비중
   상품 A를 구매 했을 때 상품 B를 구매할 확률이 어느정도 되는지를 확인합니다.


   신뢰도 c(A→B) =  P(A∩B) / P(A)  :  A와 B가 동시에 포함된 거래 수 / A가 포함된 거래 수

   : 연관성

3. 향상도(Lift)

  상품 A의 거래 중 항목 B가 포함된 거래의 비율 / 전체 상품 거래 중 상품 B가 거래된 비율
  (A가 주어지지 않았을 때 B의 확률 대비 A가 주어졌을 때 B의 확률 증가 비율)

  향상도   l(A→B) = P(A∩B) / P(A)*P(B)  = P (B|A) / P (B)

  :  A와 B가 동시에 일어난 횟수 / A, B가 독립된 사건일 때 A,B가 동시에 일어날 확률

"""

In [2]:
import pandas as pd
import numpy as np

In [137]:
EXAMPLE = pd.read_csv('data/instacart_example.csv')
PRODUCT = pd.read_csv('data/instacart_product.csv', encoding='cp949')
DEPARTMENTS = pd.read_csv('data/instacart_departments.csv')

In [4]:
EXAMPLE.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,department_id
0,2539329,1,1,2,8,NaN,196,1,0,7
1,2539329,1,1,2,8,NaN,14084,2,0,16
2,2539329,1,1,2,8,NaN,12427,3,0,19
3,2539329,1,1,2,8,NaN,26088,4,0,19
4,2539329,1,1,2,8,NaN,26405,5,0,17

In [5]:
PRODUCT.head()

,product_id,product_name,department_id
0,1,Chocolate Sandwich Cookies,19.0
1,2,All-Seasons Salt,13.0
2,3,Robust Golden Unsweetened Oolong Tea,7.0
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,1.0
4,5,Green Chile Anytime Sauce,13.0

In [6]:
DEPARTMENTS.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [7]:
DEPARTMENTS.shape

(21, 2)

In [8]:
EXAMPLE[EXAMPLE.product_id == 14084]

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,department_id
1,2539329,1,1,2,8,NaN,14084,2,0,16
17039,3241517,140,14,4,16,7.0,14084,25,0,16
45037,1204424,293,1,0,20,NaN,14084,2,0,16
45054,2748748,293,2,1,20,15.0,14084,2,1,16
45095,1216787,293,5,4,18,17.0,14084,10,1,16
45098,1249341,293,6,3,17,30.0,14084,1,1,16
45123,1055717,293,7,4,18,29.0,14084,1,1,16
45145,666649,293,8,4,17,7.0,14084,5,1,16
45562,512481,297,3,2,15,30.0,14084,2,0,16
45593,3068717,297,10,1,18,26.0,14084,3,1,16
50820,3384743,325,4,1,16,21.0,14084,7,0,16
63181,1530705,415,1,4,5,NaN,14084,7,0,16
63187,2991406,415,2,4,12,7.0,14084,5,1,16
63195,2878412,415,3,6,6,16.0,14084,6,1,16
63197,2084373,415,4,2,20,30.0,14084,1,1,16
63204,2333435,415,5,3,23,8.0,14084,3,1,16
63217,571823,415,6,5,11,9.0,14084,4,1,16
64016,1253247,423,16,2,11,7.0,14084,3,0,16
64025,3359468,423,20,2,12,14.0,14084,2,1,16
64034,2126299,423,24,2,10,7.0,14084,2,1,16
64044,3380101,423,27,2,14,7.0,14084,5,1,16
64050,970507,423,31,2,9,7.0,14084,1,1,16
64066,1800166,423,37,2,11,1.0,14084,2,1,16
64232,425731,427,2,0,21,30.0,14084,3,0,16
73473,2050671,475,16,1,8,3.0,14084,7,0,16
73641,585712,476,10,4,15,8.0,14084,7,0,16

In [9]:
PRODUCT[PRODUCT.product_id==14084]

       product_id                             product_name  department_id
14083       14084  Organic Unsweetened Vanilla Almond Milk           16.0

In [10]:
D = pd.merge(
    pd.merge(EXAMPLE, PRODUCT[['product_id','product_name']], on='product_id', how='left'),
    DEPARTMENTS,on='department_id', how='left'
    )

In [11]:
D.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,department_id,product_name,department
0,2539329,1,1,2,8,NaN,196,1,0,7,Soda,beverages
1,2539329,1,1,2,8,NaN,14084,2,0,16,Organic Unsweetened Vanilla Almond Milk,dairy eggs
2,2539329,1,1,2,8,NaN,12427,3,0,19,Original Beef Jerky,snacks
3,2539329,1,1,2,8,NaN,26088,4,0,19,Aged White Cheddar Popcorn,snacks
4,2539329,1,1,2,8,NaN,26405,5,0,17,XL Pick-A-Size Paper Towel Rolls,household

In [12]:
D.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 77425 entries, 0 to 77424
Data columns (total 12 columns):
order_id                  77425 non-null int64
user_id                   77425 non-null int64
order_number              77425 non-null int64
order_dow                 77425 non-null int64
order_hour_of_day         77425 non-null int64
days_since_prior_order    72525 non-null float64
product_id                77425 non-null int64
add_to_cart_order         77425 non-null int64
reordered                 77425 non-null int64
department_id             77425 non-null int64
product_name              77425 non-null object
department                77425 non-null object
dtypes: float64(1), int64(9), object(2)
memory usage: 7.7+ MB

In [13]:
D.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,department_id
count,7.742500e+04,77425.000000,77425.000000,77425.000000,77425.000000,72525.00000,77425.000000,77425.000000,77425.000000,77425.000000
mean,1.696186e+06,260.848576,16.878579,2.759755,13.520052,11.08080,25815.593323,8.360452,0.583687,10.010216
std,9.880130e+05,140.175786,17.531267,2.087571,4.273775,8.82473,14216.871937,7.193211,0.492950,6.247321
min,4.000000e+01,1.000000,1.000000,0.000000,0.000000,0.00000,1.000000,1.000000,0.000000,1.000000
25%,8.567530e+05,149.000000,5.000000,1.000000,10.000000,5.00000,13535.000000,3.000000,0.000000,4.000000
50%,1.671477e+06,262.000000,11.000000,3.000000,13.000000,7.00000,25740.000000,6.000000,1.000000,9.000000
75%,2.564286e+06,381.000000,23.000000,5.000000,17.000000,15.00000,38293.000000,11.000000,1.000000,16.000000
max,3.420572e+06,500.000000,99.000000,6.000000,23.000000,30.00000,49683.000000,89.000000,1.000000,21.000000

In [14]:
# Q1: 현재 구매데이터 셋을 바탕으로 요일별 방문자수를 확인하고
#  (이때 방문자수는 user_id가 아닌 order_id를 기준으로 확인한다)
#  가장 많은 방문자를 기록한 요일을 먼저 확인한다.
#  그후 해당 요일에 가장 많이 팔린 상품ID 및 판매 수를 확인하라

In [15]:
EXAMPLE.groupby(by='order_id').max()[['order_dow']]

          order_dow
order_id
40                1
1483              3
2199              4
2593              6
3449              1
4163              2
4307              3
4595              3
4890              2
5640              2
6524              1
7099              3
8382              0
10077             5
10423             3
10837             5
10985             1
11348             0
12218             3
12278             3
12404             2
12659             3
13107             0
13118             2
13731             2
14197             1
14400             1
16785             0
18296             0
18331             2
...             ...
3406808           1
3407043           5
3407614           1
3408134           0
3408259           5
3408319           2
3409449           2
3410306           1
3411352           6
3411559           1
3412510           1
3412920           2
3413508           4
3413579           3
3413875           2
3413994           2
3414050           2
3414536           3
3415043           3
3415050           4
3415661           4
3415986           0
3416568           6
3417147           3
3417221           2
3417487           5
3417792           4
3418806           5
3419231           6
3420572           1

[7642 rows x 1 columns]

In [16]:
D11 = EXAMPLE.groupby(by='order_id').max()[['order_dow']]

In [17]:
D11.reset_index().groupby(by='order_dow').agg('count').sort_values('order_id',ascending=False)

           order_id
order_dow
1              1424
0              1248
2              1089
5              1082
3               968
4               924
6               907

In [18]:
D[D.order_dow == 1].groupby(by=['product_id','product_name']).agg('count').sort_values('order_id', ascending=False)

,,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,department_id,department
product_id,product_name,,,,,,,,,,
13176,Bag of Organic Bananas,183,183,183,183,183,174,183,183,183,183
24852,Banana,156,156,156,156,156,145,156,156,156,156
21137,Organic Strawberries,146,146,146,146,146,138,146,146,146,146
47209,Organic Hass Avocado,129,129,129,129,129,122,129,129,129,129
21903,Organic Baby Spinach,111,111,111,111,111,103,111,111,111,111
47766,Organic Avocado,90,90,90,90,90,87,90,90,90,90
45007,Organic Zucchini,65,65,65,65,65,62,65,65,65,65
39275,Organic Blueberries,60,60,60,60,60,55,60,60,60,60
27966,Organic Raspberries,59,59,59,59,59,58,59,59,59,59
26209,Limes,58,58,58,58,58,56,58,58,58,58
24964,Organic Garlic,55,55,55,55,55,53,55,55,55,55
22935,Organic Yellow Onion,55,55,55,55,55,53,55,55,55,55
30391,Organic Cucumber,54,54,54,54,54,50,54,54,54,54
16797,Strawberries,52,52,52,52,52,48,52,52,52,52
49235,Organic Half & Half,51,51,51,51,51,45,51,51,51,51
27086,Half & Half,51,51,51,51,51,49,51,51,51,51
8277,Apple Honeycrisp Organic,51,51,51,51,51,50,51,51,51,51
47626,Large Lemon,50,50,50,50,50,48,50,50,50,50
49683,Cucumber Kirby,46,46,46,46,46,45,46,46,46,46
35951,Organic Unsweetened Almond Milk,45,45,45,45,45,43,45,45,45,45
4920,Seedless Red Grapes,44,44,44,44,44,42,44,44,44,44
5876,Organic Lemon,43,43,43,43,43,42,43,43,43,43
27104,Fresh Cauliflower,39,39,39,39,39,37,39,39,39,39
27845,Organic Whole Milk,37,37,37,37,37,33,37,37,37,37
42265,Organic Baby Carrots,37,37,37,37,37,34,37,37,37,37
44359,Organic Small Bunch Celery,36,36,36,36,36,35,36,36,36,36
40396,Guacamole,36,36,36,36,36,34,36,36,36,36
33731,Grated Parmesan,35,35,35,35,35,33,35,35,35,35
8518,Organic Red Onion,35,35,35,35,35,35,35,35,35,35
19057,Organic Large Extra Fancy Fuji Apple,35,35,35,35,35,32,35,35,35,35
...,...,...,...,...,...,...,...,...,...,...,...
26049,Sterile Saline Nasal Mist for Dry or Stuffy Nose,1,1,1,1,1,1,1,1,1,1
26063,Golden Milk Supplement,1,1,1,1,1,1,1,1,1,1
26066,French Lavendar Leave In Conditioner,1,1,1,1,1,1,1,1,1,1
26091,Blast of Vitamin C Very Berry,1,1,1,1,1,1,1,1,1,1
26104,Frozen Organic Mango Chunks,1,1,1,1,1,1,1,1,1,1
26118,Oven Ready Lasagna,1,1,1,1,1,1,1,1,1,1
5459,Chamomile Tea,1,1,1,1,1,1,1,1,1,1
25843,Maple Bacon Potato Chips,1,1,1,1,1,1,1,1,1,1
25839,Froot Loops Cereal,1,1,1,1,1,1,1,1,1,1
25832,Morning Rounds Muesli Fruit & Grain Buns,1,1,1,1,1,1,1,1,1,1
25630,Healthy Grains Fiber Cinnamon Oat Clusters,1,1,1,1,1,1,1,1,1,1
25506,Tall Compostable Kitchen Bags,1,1,1,1,1,1,1,1,1,1
25512,Original Brown N' Serve Sausage Links,1,1,1,1,1,1,1,1,1,1
5578,Okra,1,1,1,1,1,1,1,1,1,1
25535,Organic Creamy Peanut Butter Hint of Sea Salt,1,1,1,1,1,0,1,1,1,1
5550,YoBaby Peach Pear Yogurt,1,1,1,1,1,1,1,1,1,1
25565,Jumbo Cheese Puffs,1,1,1,1,1,1,1,1,1,1
5547,Roasted Sesame Seaweed Snacks,1,1,1,1,1,1,1,1,1,1
25610,Organic Pomegranate Kernels,1,1,1,1,1,1,1,1,1,1
5539,Organic SprouTofu Silken Tofu,1,1,1,1,1,1,1,1,1,1
25817,Zero Calorie Grape Soda,1,1,1,1,1,1,1,1,1,1
25666,Madras Curry Spicy Indian Simmer Sauce,1,1,1,1,1,1,1,1,1,1
25676,Condensed Soup Bean with Bacon,1,1,1,1,1,1,1,1,1,1
25713,Smart Ones Anytime Selections Mini Cheeseburger,1,1,1,1,1,1,1,1,1,1
5535,Large Brown Free Range Eggs Grade A,1,1,1,1,1,1,1,1,1,1
25740,Pepperidge Farm짰 Goldfish Xtra Cheddar Baked Snack Crackers,1,1,1,1,1,1,1,1,1,1
25743,Organic Beef Stock,1,1,1,1,1,1,1,1,1,1
25753,Organic Homestyle Waffles,1,1,1,1,1,1,1,1,1,1
25804,Original Soy Milk,1,1,1,1,1,1,1,1,1,1
24990,Go Mango! Organic Dried Chili Lime Mango,1,1,1,1,1,1,1,1,1,1

In [3]:
# Q2
_ = """
Q2: Q1을 통해 확인한 요일의 판매 데이터만 추출해 연관성 분석을 진행하고자 한다. 
    주문 내역(order_id) 내 상품 코너(department) 간 연관성을 확인하고자 하며 
    선행, 후행 단일 항목으로 구성된 규칙을 추출하고자 한다.
   이때 제시된 연관규칙 중 babies 코너와 Lift 값이 가장 높게 나온 코너는 무엇인가? 
   (Min Supprot: 0.03 confidence: 0.85 나머지 default 값 ) 
"""

In [44]:
D[D.order_dow == 1].department.value_counts().head()

produce       4099
dairy eggs    2440
snacks        1418
beverages     1252
frozen         880
Name: department, dtype: int64

In [45]:
D[D.order_dow == 1].groupby(by='order_id').department.agg(lambda x: list(x))

order_id
40               [dairy eggs, frozen, beverages, dairy eggs]
3449       [meat seafood, beverages, produce, beverages, ...
6524       [pantry, pantry, produce, beverages, beverages...
10985                     [beverages, beverages, dairy eggs]
14197       [produce, snacks, snacks, canned goods, produce]
14400                              [snacks, snacks, alcohol]
19190      [canned goods, frozen, frozen, frozen, frozen,...
19256      [dairy eggs, bakery, dry goods pasta, pantry, ...
19682      [produce, produce, produce, snacks, snacks, pa...
29171                     [frozen, produce, produce, pantry]
30057      [deli, snacks, snacks, snacks, produce, produc...
30855      [deli, pets, beverages, dairy eggs, dry goods ...
31801      [frozen, snacks, produce, meat seafood, dairy ...
33104      [babies, breakfast, breakfast, breakfast, babi...
34164      [pets, beverages, dairy eggs, dairy eggs, dry ...
46306      [pantry, pantry, pantry, dry goods pasta, prod...
46584                                               [snacks]
48109      [bakery, frozen, beverages, frozen, frozen, pr...
49068      [dairy eggs, dairy eggs, dairy eggs, dairy egg...
52830      [dairy eggs, dairy eggs, dairy eggs, dairy egg...
53644      [dairy eggs, breakfast, snacks, breakfast, sna...
58931                   [produce, produce, produce, produce]
62373      [snacks, alcohol, alcohol, dairy eggs, dairy e...
62412                             [produce, produce, snacks]
63865      [produce, produce, dairy eggs, produce, produc...
65234      [produce, produce, produce, deli, beverages, b...
65779      [produce, deli, snacks, snacks, snacks, produc...
66352      [beverages, dairy eggs, pantry, frozen, frozen...
68264      [dairy eggs, snacks, beverages, dairy eggs, da...
73511      [dairy eggs, beverages, bakery, dairy eggs, da...
                                 ...
3366824                           [frozen, produce, produce]
3367490    [produce, produce, meat seafood, household, ho...
3369087    [bakery, dairy eggs, dairy eggs, produce, froz...
3372845    [household, household, frozen, household, pers...
3374094    [dairy eggs, dairy eggs, dairy eggs, dairy egg...
3374781    [dairy eggs, produce, dairy eggs, deli, dairy ...
3375628    [dairy eggs, dairy eggs, dairy eggs, dairy egg...
3377351    [produce, produce, produce, dairy eggs, produc...
3378475    [dry goods pasta, pantry, dry goods pasta, pro...
3379591                               [bulk, snacks, snacks]
3380654    [dairy eggs, produce, beverages, produce, deli...
3381147                    [bakery, produce, pantry, pantry]
3382984    [produce, dairy eggs, dairy eggs, produce, pro...
3384743    [dairy eggs, produce, personal care, beverages...
3385659    [dairy eggs, dairy eggs, beverages, beverages,...
3386779    [snacks, snacks, snacks, beverages, beverages,...
3386821                    [produce, dairy eggs, dairy eggs]
3387727       [snacks, produce, breakfast, produce, produce]
3388703    [produce, snacks, produce, dairy eggs, snacks,...
3391303    [household, produce, produce, dairy eggs, dair...
3392287                                         [dairy eggs]
3392471    [produce, produce, produce, snacks, internatio...
3401727    [frozen, dairy eggs, produce, produce, produce...
3406365    [produce, produce, produce, produce, produce, ...
3406808    [produce, pantry, produce, produce, produce, p...
3407614    [dairy eggs, dairy eggs, frozen, dairy eggs, d...
3410306     [international, beverages, beverages, beverages]
3411559    [dairy eggs, produce, babies, produce, bakery,...
3412510    [frozen, produce, produce, dairy eggs, dairy e...
3420572    [produce, dairy eggs, dairy eggs, beverages, p...
Name: department, Length: 1424, dtype: object

In [54]:
D[D.order_dow == 1].groupby(by='order_id').department.agg(lambda x: list(set(x))).values

array([list(['dairy eggs', 'frozen', 'beverages']),
       list(['produce', 'beverages', 'meat seafood']),
       list(['produce', 'dairy eggs', 'pantry', 'beverages', 'meat seafood']),
       ...,
       list(['babies', 'produce', 'bakery', 'dairy eggs', 'dry goods pasta', 'meat seafood']),
       list(['produce', 'dairy eggs', 'deli', 'frozen', 'meat seafood']),
       list(['produce', 'bakery', 'dairy eggs', 'snacks', 'canned goods', 'pantry', 'beverages'])],
      dtype=object)

In [55]:
records = D[D.order_dow == 1].groupby(by='order_id').department.agg(lambda x: list(set(x))).values

In [22]:
from apyori import apriori

In [56]:
association_rules = apriori(records, min_support=0.03, min_confidence=0.85)

In [57]:
# association_results = list(association_rules)
association_results = list(association_rules)

In [58]:
association_results

[RelationRecord(items=frozenset({'dairy eggs', 'babies'}), support=0.047050561797752806, ordered_statistics=[OrderedStatistic(items_base=frozenset({'babies'}), items_add=frozenset({'dairy eggs'}), confidence=0.9178082191780821, lift=1.37429958371145)]),
 RelationRecord(items=frozenset({'babies', 'produce'}), support=0.04564606741573034, ordered_statistics=[OrderedStatistic(items_base=frozenset({'babies'}), items_add=frozenset({'produce'}), confidence=0.8904109589041096, lift=1.2334097329566653)]),
 RelationRecord(items=frozenset({'produce', 'canned goods'}), support=0.17907303370786518, ordered_statistics=[OrderedStatistic(items_base=frozenset({'canned goods'}), items_add=frozenset({'produce'}), confidence=0.9172661870503597, lift=1.2706099711670351)]),
 RelationRecord(items=frozenset({'produce', 'deli'}), support=0.19241573033707865, ordered_statistics=[OrderedStatistic(items_base=frozenset({'deli'}), items_add=frozenset({'produce'}), confidence=0.8698412698412699, lift=1.2049163115310975)]),
 RelationRecord(items=frozenset({'produce', 'dry goods pasta'}), support=0.14747191011235955, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dry goods pasta'}), items_add=frozenset({'produce'}), confidence=0.8786610878661087, lift=1.2171336470051934)]),
 RelationRecord(items=frozenset({'produce', 'meat seafood'}), support=0.1544943820224719, ordered_statistics=[OrderedStatistic(items_base=frozenset({'meat seafood'}), items_add=frozenset({'produce'}), confidence=0.8979591836734694, lift=1.2438656396410703)]),
 RelationRecord(items=frozenset({'pantry', 'produce'}), support=0.2731741573033708, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pantry'}), items_add=frozenset({'produce'}), confidence=0.858719646799117, lift=1.1895104835038353)]),
 RelationRecord(items=frozenset({'dairy eggs', 'babies', 'produce'}), support=0.042134831460674156, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dairy eggs', 'babies'}), items_add=frozenset({'produce'}), confidence=0.8955223880597015, lift=1.240490156222777), OrderedStatistic(items_base=frozenset({'babies', 'produce'}), items_add=frozenset({'dairy eggs'}), confidence=0.923076923076923, lift=1.382188789128852)]),
 RelationRecord(items=frozenset({'dairy eggs', 'bakery', 'breakfast'}), support=0.051264044943820225, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bakery', 'breakfast'}), items_add=frozenset({'dairy eggs'}), confidence=0.8902439024390244, lift=1.3330255700033342)]),
 RelationRecord(items=frozenset({'bakery', 'breakfast', 'produce'}), support=0.04915730337078652, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bakery', 'breakfast'}), items_add=frozenset({'produce'}), confidence=0.8536585365853658, lift=1.182499762740818)]),
 RelationRecord(items=frozenset({'bakery', 'canned goods', 'produce'}), support=0.05758426966292135, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bakery', 'canned goods'}), items_add=frozenset({'produce'}), confidence=0.9111111111111111, lift=1.2620838737570255)]),
 RelationRecord(items=frozenset({'dairy eggs', 'bakery', 'household'}), support=0.03441011235955056, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bakery', 'household'}), items_add=frozenset({'dairy eggs'}), confidence=0.890909090909091, lift=1.3340216040531498)]),
 RelationRecord(items=frozenset({'dairy eggs', 'bakery', 'snacks'}), support=0.12078651685393259, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bakery', 'snacks'}), items_add=frozenset({'dairy eggs'}), confidence=0.8643216080402011, lift=1.2942102732379035)]),
 RelationRecord(items=frozenset({'bakery', 'deli', 'produce'}), support=0.07303370786516854, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bakery', 'deli'}), items_add=frozenset({'produce'}), confidence=0.9285714285714286, lift=1.2862701500833795)]),
 RelationRecord(items=frozenset({'bakery', 'dry goods pasta', 'produce'}), support=0.059691011235955056, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bakery', 'dry goods pasta'}), items_add=frozenset({'produce'}), confidence=0.9239130434782608, lift=1.2798172897986801)]),
 RelationRecord(items=frozenset({'bakery', 'frozen', 'produce'}), support=0.09410112359550561, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bakery', 'frozen'}), items_add=frozenset({'produce'}), confidence=0.8993288590604026, lift=1.2457629331731646)]),
 RelationRecord(items=frozenset({'bakery', 'produce', 'meat seafood'}), support=0.05688202247191011, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bakery', 'meat seafood'}), items_add=frozenset({'produce'}), confidence=0.9310344827586208, lift=1.2896820072454045)]),
 RelationRecord(items=frozenset({'bakery', 'pantry', 'produce'}), support=0.09901685393258428, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bakery', 'pantry'}), items_add=frozenset({'produce'}), confidence=0.875776397515528, lift=1.2131377335234552)]),
 RelationRecord(items=frozenset({'dairy eggs', 'breakfast', 'beverages'}), support=0.07443820224719101, ordered_statistics=[OrderedStatistic(items_base=frozenset({'breakfast', 'beverages'}), items_add=frozenset({'dairy eggs'}), confidence=0.8760330578512396, lift=1.3117466607572716)]),
 RelationRecord(items=frozenset({'produce', 'canned goods', 'beverages'}), support=0.08918539325842696, ordered_statistics=[OrderedStatistic(items_base=frozenset({'canned goods', 'beverages'}), items_add=frozenset({'produce'}), confidence=0.8943661971830986, lift=1.238888584424837)]),
 RelationRecord(items=frozenset({'produce', 'deli', 'beverages'}), support=0.09831460674157304, ordered_statistics=[OrderedStatistic(items_base=frozenset({'deli', 'beverages'}), items_add=frozenset({'produce'}), confidence=0.8588957055214724, lift=1.1897543625122342)]),
 RelationRecord(items=frozenset({'produce', 'beverages', 'meat seafood'}), support=0.07584269662921349, ordered_statistics=[OrderedStatistic(items_base=frozenset({'beverages', 'meat seafood'}), items_add=frozenset({'produce'}), confidence=0.864, lift=1.1968249027237354)]),
 RelationRecord(items=frozenset({'dairy eggs', 'breakfast', 'canned goods'}), support=0.042837078651685394, ordered_statistics=[OrderedStatistic(items_base=frozenset({'breakfast', 'canned goods'}), items_add=frozenset({'dairy eggs'}), confidence=0.9242424242424242, lift=1.3839339769939139)]),
 RelationRecord(items=frozenset({'produce', 'breakfast', 'canned goods'}), support=0.04424157303370786, ordered_statistics=[OrderedStatistic(items_base=frozenset({'breakfast', 'canned goods'}), items_add=frozenset({'produce'}), confidence=0.9545454545454545, lift=1.3222497347010964)]),
 RelationRecord(items=frozenset({'dairy eggs', 'breakfast', 'dry goods pasta'}), support=0.04073033707865169, ordered_statistics=[OrderedStatistic(items_base=frozenset({'breakfast', 'dry goods pasta'}), items_add=frozenset({'dairy eggs'}), confidence=0.9508196721311476, lift=1.4237299822447467)]),
 RelationRecord(items=frozenset({'dairy eggs', 'breakfast', 'frozen'}), support=0.05407303370786517, ordered_statistics=[OrderedStatistic(items_base=frozenset({'breakfast', 'frozen'}), items_add=frozenset({'dairy eggs'}), confidence=0.8953488372093023, lift=1.3406695522461056)]),
 RelationRecord(items=frozenset({'dairy eggs', 'breakfast', 'meat seafood'}), support=0.030196629213483147, ordered_statistics=[OrderedStatistic(items_base=frozenset({'breakfast', 'meat seafood'}), items_add=frozenset({'dairy eggs'}), confidence=0.9148936170212767, lift=1.369935342416717)]),
 RelationRecord(items=frozenset({'dairy eggs', 'breakfast', 'pantry'}), support=0.06390449438202248, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pantry', 'breakfast'}), items_add=frozenset({'dairy eggs'}), confidence=0.9285714285714286, lift=1.3904161033498574)]),
 RelationRecord(items=frozenset({'dairy eggs', 'breakfast', 'produce'}), support=0.11235955056179775, ordered_statistics=[OrderedStatistic(items_base=frozenset({'produce', 'breakfast'}), items_add=frozenset({'dairy eggs'}), confidence=0.8602150537634408, lift=1.2880612371810092)]),
 RelationRecord(items=frozenset({'snacks', 'dairy eggs', 'breakfast'}), support=0.08567415730337079, ordered_statistics=[OrderedStatistic(items_base=frozenset({'snacks', 'breakfast'}), items_add=frozenset({'dairy eggs'}), confidence=0.8591549295774649, lift=1.2864738377689904)]),
 RelationRecord(items=frozenset({'produce', 'deli', 'breakfast'}), support=0.03089887640449438, ordered_statistics=[OrderedStatistic(items_base=frozenset({'deli', 'breakfast'}), items_add=frozenset({'produce'}), confidence=0.9565217391304347, lift=1.324987311791575)]),
 RelationRecord(items=frozenset({'produce', 'breakfast', 'dry goods pasta'}), support=0.042134831460674156, ordered_statistics=[OrderedStatistic(items_base=frozenset({'breakfast', 'dry goods pasta'}), items_add=frozenset({'produce'}), confidence=0.9836065573770492, lift=1.3625055814250175)]),
 RelationRecord(items=frozenset({'produce', 'breakfast', 'frozen'}), support=0.054775280898876406, ordered_statistics=[OrderedStatistic(items_base=frozenset({'breakfast', 'frozen'}), items_add=frozenset({'produce'}), confidence=0.9069767441860466, lift=1.256356890779115)]),
 RelationRecord(items=frozenset({'produce', 'breakfast', 'meat seafood'}), support=0.030196629213483147, ordered_statistics=[OrderedStatistic(items_base=frozenset({'breakfast', 'meat seafood'}), items_add=frozenset({'produce'}), confidence=0.9148936170212767, lift=1.2673234539283054)]),
 RelationRecord(items=frozenset({'pantry', 'breakfast', 'produce'}), support=0.0625, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pantry', 'breakfast'}), items_add=frozenset({'produce'}), confidence=0.9081632653061225, lift=1.2580004764551735)]),
 RelationRecord(items=frozenset({'dairy eggs', 'canned goods', 'produce'}), support=0.14536516853932585, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dairy eggs', 'canned goods'}), items_add=frozenset({'produce'}), confidence=0.9539170506912443, lift=1.3213792608797001)]),
 RelationRecord(items=frozenset({'produce', 'deli', 'canned goods'}), support=0.06601123595505617, ordered_statistics=[OrderedStatistic(items_base=frozenset({'deli', 'canned goods'}), items_add=frozenset({'produce'}), confidence=0.9494949494949494, lift=1.3152537043587624)]),
 RelationRecord(items=frozenset({'produce', 'canned goods', 'dry goods pasta'}), support=0.07162921348314606, ordered_statistics=[OrderedStatistic(items_base=frozenset({'canned goods', 'dry goods pasta'}), items_add=frozenset({'produce'}), confidence=0.9444444444444443, lift=1.3082576740164287)]),
 RelationRecord(items=frozenset({'frozen', 'canned goods', 'produce'}), support=0.08356741573033707, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen', 'canned goods'}), items_add=frozenset({'produce'}), confidence=0.9296875, lift=1.2878161478599222)]),
 RelationRecord(items=frozenset({'produce', 'household', 'canned goods'}), support=0.03300561797752809, ordered_statistics=[OrderedStatistic(items_base=frozenset({'household', 'canned goods'}), items_add=frozenset({'produce'}), confidence=0.9399999999999998, lift=1.3021011673151748)]),
 RelationRecord(items=frozenset({'produce', 'canned goods', 'meat seafood'}), support=0.054775280898876406, ordered_statistics=[OrderedStatistic(items_base=frozenset({'canned goods', 'meat seafood'}), items_add=frozenset({'produce'}), confidence=0.9512195121951219, lift=1.31764259276834)]),
 RelationRecord(items=frozenset({'pantry', 'canned goods', 'produce'}), support=0.09199438202247191, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pantry', 'canned goods'}), items_add=frozenset({'produce'}), confidence=0.9562043795620438, lift=1.3245477008719362)]),
 RelationRecord(items=frozenset({'produce', 'snacks', 'canned goods'}), support=0.08707865168539326, ordered_statistics=[OrderedStatistic(items_base=frozenset({'snacks', 'canned goods'}), items_add=frozenset({'produce'}), confidence=0.9465648854961832, lift=1.3111949386639736)]),
 RelationRecord(items=frozenset({'dairy eggs', 'deli', 'dry goods pasta'}), support=0.047050561797752806, ordered_statistics=[OrderedStatistic(items_base=frozenset({'deli', 'dry goods pasta'}), items_add=frozenset({'dairy eggs'}), confidence=0.8701298701298701, lift=1.3029073975446215)]),
 RelationRecord(items=frozenset({'dairy eggs', 'deli', 'produce'}), support=0.1601123595505618, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dairy eggs', 'deli'}), items_add=frozenset({'produce'}), confidence=0.8735632183908046, lift=1.2100720067981574)]),
 RelationRecord(items=frozenset({'dairy eggs', 'deli', 'snacks'}), support=0.10533707865168539, ordered_statistics=[OrderedStatistic(items_base=frozenset({'deli', 'snacks'}), items_add=frozenset({'dairy eggs'}), confidence=0.8982035928143712, lift=1.3449441810385538)]),
 RelationRecord(items=frozenset({'dairy eggs', 'frozen', 'dry goods pasta'}), support=0.06952247191011236, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen', 'dry goods pasta'}), items_add=frozenset({'dairy eggs'}), confidence=0.868421052631579, lift=1.3003486634567492)]),
 RelationRecord(items=frozenset({'dairy eggs', 'dry goods pasta', 'produce'}), support=0.125, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dairy eggs', 'dry goods pasta'}), items_add=frozenset({'produce'}), confidence=0.9270833333333334, lift=1.2842088197146562)]),
 RelationRecord(items=frozenset({'dairy eggs', 'snacks', 'dry goods pasta'}), support=0.07092696629213484, ordered_statistics=[OrderedStatistic(items_base=frozenset({'snacks', 'dry goods pasta'}), items_add=frozenset({'dairy eggs'}), confidence=0.8559322033898307, lift=1.2816482204280955)]),
 RelationRecord(items=frozenset({'dairy eggs', 'household', 'frozen'}), support=0.0449438202247191, ordered_statistics=[OrderedStatistic(items_base=frozenset({'household', 'frozen'}), items_add=frozenset({'dairy eggs'}), confidence=0.8533333333333334, lift=1.2777567472835611)]),
 RelationRecord(items=frozenset({'dairy eggs', 'frozen', 'produce'}), support=0.20575842696629212, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dairy eggs', 'frozen'}), items_add=frozenset({'produce'}), confidence=0.8617647058823529, lift=1.1937285420004575)]),
 RelationRecord(items=frozenset({'dairy eggs', 'produce', 'international'}), support=0.04143258426966292, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dairy eggs', 'international'}), items_add=frozenset({'produce'}), confidence=0.8939393939393938, lift=1.2382973705930902)]),
 RelationRecord(items=frozenset({'dairy eggs', 'produce', 'meat seafood'}), support=0.125, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dairy eggs', 'meat seafood'}), items_add=frozenset({'produce'}), confidence=0.9368421052631579, lift=1.2977268072906)]),
 RelationRecord(items=frozenset({'dairy eggs', 'snacks', 'meat seafood'}), support=0.059691011235955056, ordered_statistics=[OrderedStatistic(items_base=frozenset({'snacks', 'meat seafood'}), items_add=frozenset({'dairy eggs'}), confidence=0.8673469387755102, lift=1.2987403163158007)]),
 RelationRecord(items=frozenset({'dairy eggs', 'pantry', 'produce'}), support=0.21418539325842698, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dairy eggs', 'pantry'}), items_add=frozenset({'produce'}), confidence=0.8815028901734104, lift=1.221070151368615)]),
 RelationRecord(items=frozenset({'produce', 'deli', 'dry goods pasta'}), support=0.05196629213483146, ordered_statistics=[OrderedStatistic(items_base=frozenset({'deli', 'dry goods pasta'}), items_add=frozenset({'produce'}), confidence=0.961038961038961, lift=1.3312446308555257)]),
 RelationRecord(items=frozenset({'produce', 'deli', 'frozen'}), support=0.08426966292134831, ordered_statistics=[OrderedStatistic(items_base=frozenset({'deli', 'frozen'}), items_add=frozenset({'produce'}), confidence=0.9022556390977443, lift=1.2498171498785873)]),
 RelationRecord(items=frozenset({'produce', 'deli', 'meat seafood'}), support=0.04915730337078652, ordered_statistics=[OrderedStatistic(items_base=frozenset({'deli', 'meat seafood'}), items_add=frozenset({'produce'}), confidence=0.9459459459459459, lift=1.3103375749290145)]),
 RelationRecord(items=frozenset({'pantry', 'deli', 'produce'}), support=0.08707865168539326, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pantry', 'deli'}), items_add=frozenset({'produce'}), confidence=0.911764705882353, lift=1.2629892423895628)]),
 RelationRecord(items=frozenset({'produce', 'deli', 'snacks'}), support=0.10252808988764045, ordered_statistics=[OrderedStatistic(items_base=frozenset({'deli', 'snacks'}), items_add=frozenset({'produce'}), confidence=0.874251497005988, lift=1.2110254199771662)]),
 RelationRecord(items=frozenset({'produce', 'frozen', 'dry goods pasta'}), support=0.07303370786516854, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen', 'dry goods pasta'}), items_add=frozenset({'produce'}), confidence=0.9122807017543859, lift=1.2637040070994605)]),
 RelationRecord(items=frozenset({'produce', 'dry goods pasta', 'meat seafood'}), support=0.051264044943820225, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dry goods pasta', 'meat seafood'}), items_add=frozenset({'produce'}), confidence=0.8902439024390244, lift=1.2331783240011387)]),
 RelationRecord(items=frozenset({'pantry', 'dry goods pasta', 'produce'}), support=0.07724719101123595, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pantry', 'dry goods pasta'}), items_add=frozenset({'produce'}), confidence=0.9322033898305084, lift=1.2913011936951788)]),
 RelationRecord(items=frozenset({'produce', 'snacks', 'dry goods pasta'}), support=0.07514044943820225, ordered_statistics=[OrderedStatistic(items_base=frozenset({'snacks', 'dry goods pasta'}), items_add=frozenset({'produce'}), confidence=0.9067796610169493, lift=1.2560838884125833)]),
 RelationRecord(items=frozenset({'produce', 'household', 'frozen'}), support=0.04564606741573034, ordered_statistics=[OrderedStatistic(items_base=frozenset({'household', 'frozen'}), items_add=frozenset({'produce'}), confidence=0.8666666666666667, lift=1.2005188067444876)]),
 RelationRecord(items=frozenset({'produce', 'frozen', 'meat seafood'}), support=0.06671348314606741, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen', 'meat seafood'}), items_add=frozenset({'produce'}), confidence=0.9313725490196079, lift=1.2901503013656823)]),
 RelationRecord(items=frozenset({'pantry', 'frozen', 'produce'}), support=0.11446629213483146, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pantry', 'frozen'}), items_add=frozenset({'produce'}), confidence=0.8810810810810811, lift=1.2204858555053106)]),
 RelationRecord(items=frozenset({'pantry', 'produce', 'meat seafood'}), support=0.07092696629213484, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pantry', 'meat seafood'}), items_add=frozenset({'produce'}), confidence=0.90990990990991, lift=1.260419953026957)]),
 RelationRecord(items=frozenset({'produce', 'snacks', 'meat seafood'}), support=0.061095505617977525, ordered_statistics=[OrderedStatistic(items_base=frozenset({'snacks', 'meat seafood'}), items_add=frozenset({'produce'}), confidence=0.8877551020408162, lift=1.2297308028269671)]),
 RelationRecord(items=frozenset({'pantry', 'personal care', 'produce'}), support=0.03300561797752809, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pantry', 'personal care'}), items_add=frozenset({'produce'}), confidence=0.8545454545454545, lift=1.1837283339228863)]),
 RelationRecord(items=frozenset({'pantry', 'snacks', 'produce'}), support=0.14536516853932585, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pantry', 'snacks'}), items_add=frozenset({'produce'}), confidence=0.8922413793103449, lift=1.2359452569435128)]),

In [90]:
for x in association_results:

    if 'babies' in x[0]:
        print("item", x[0]) # items
        print("\tsupport", x[1]) # support
        print("\tlift", x[2][0].lift)  # lify

item frozenset({'dairy eggs', 'babies'})
	support 0.047050561797752806
	lift 1.37429958371145
item frozenset({'babies', 'produce'})
	support 0.04564606741573034
	lift 1.2334097329566653
item frozenset({'dairy eggs', 'babies', 'produce'})
	support 0.042134831460674156
	lift 1.240490156222777

In [4]:
# Q3
_ = """
Q3: 구매한 상품이 재구매 상품인지 분류하는 Decision Tree 모델을 만들고자한다. 
먼저 데이터 분할은 고객(user_id)별 가장 마지막 주문 내역의 구매 상품들을 테스트셋으로 나머지는 트레인셋으로 구분한다.

다음으로 트레인셋 DB를 대상으로 상품(product_id)별 재구매 비중을 확인하여 
테스트셋, 트레인셋 동일하게 상품의 재구매 비율(reordered_rate) 변수로 추가한다. 
(테스트셋 join 후 재구매 비율의 결측치는 0으로 변환한다)

트레인셋 총 72,155행, 테스트셋 총 5,270셋
독립변수: 구매 요일(order_dow), 구매 시간(order_hour_of_day), 이전 구매일(days_since_prior), 
상품의 재구매 비율(reordered_rate) 
종속변수: reordered

트레인셋에 맞춰 모델을 만들어 테스트셋으로 예측을 한 후 재구매 예측에 대한 재현율(recall)을 구하여라 
(Criterion: Gini, Splitter: Best, Max Depth:6, Seed: 13, Max Leaf Nodes: 25, 나머지 default) 

ex) 0.48(둘째자리만 나타냄, 셋째자리 버림)
"""

In [92]:
D.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,department_id,product_name,department
0,2539329,1,1,2,8,NaN,196,1,0,7,Soda,beverages
1,2539329,1,1,2,8,NaN,14084,2,0,16,Organic Unsweetened Vanilla Almond Milk,dairy eggs
2,2539329,1,1,2,8,NaN,12427,3,0,19,Original Beef Jerky,snacks
3,2539329,1,1,2,8,NaN,26088,4,0,19,Aged White Cheddar Popcorn,snacks
4,2539329,1,1,2,8,NaN,26405,5,0,17,XL Pick-A-Size Paper Towel Rolls,household

In [98]:
last_order_id = D.groupby(by='user_id').order_id.max()

In [104]:
D[D.order_id.isin(last_order_id)].order_id.nunique()

500

In [105]:
D[~D.order_id.isin(last_order_id)].order_id.nunique()

7142

In [108]:
D['last'] = D.order_id.isin(last_order_id)

In [107]:
D.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,department_id,product_name,department,last
0,2539329,1,1,2,8,NaN,196,1,0,7,Soda,beverages,False
1,2539329,1,1,2,8,NaN,14084,2,0,16,Organic Unsweetened Vanilla Almond Milk,dairy eggs,False
2,2539329,1,1,2,8,NaN,12427,3,0,19,Original Beef Jerky,snacks,False
3,2539329,1,1,2,8,NaN,26088,4,0,19,Aged White Cheddar Popcorn,snacks,False
4,2539329,1,1,2,8,NaN,26405,5,0,17,XL Pick-A-Size Paper Towel Rolls,household,False

In [109]:
pd.crosstab( D['product_id'], D['reordered'])

reordered    0    1
product_id
1            1    1
9            1    0
10           5    8
13           1    0
23           2    0
25           2    5
29           1    1
30           1    0
34           8   11
35           1    0
36           1    0
45          12   17
49           3    0
54           4    1
60           1    0
70           1    2
77           3   10
79           8   11
93           1    0
95          13    0
96           1    0
99           1    1
100          2    2
106          1    0
111          1    1
116          6    3
117          3   27
118          1    0
122          1    0
123          2    0
...         ..  ...
49583        3    0
49585        9    8
49586        1    0
49588        2    0
49598        1    0
49600        2    1
49605        2    1
49609        1    0
49610        3   14
49615        2   22
49617        1    0
49620        1    1
49621        3    1
49622        1    0
49628        6    5
49630        1    0
49634        2    0
49640        1    2
49652        2    0
49655        2    0
49659        1    0
49662        1    0
49667        1    0
49668        1    0
49670        1    0
49674        1    0
49677        2    1
49678        1    0
49680        1    0
49683       77  197

[10833 rows x 2 columns]

In [111]:
D31 = D.groupby(by='product_id').reordered.agg(['count',np.sum])
D31['reorder_rate'] = D31['sum']/D31['count']
D31.head()

            count  sum  reorder_rate
product_id
1               2    1      0.500000
9               1    0      0.000000
10             13    8      0.615385
13              1    0      0.000000
23              2    0      0.000000

In [113]:
D32 = pd.merge(D, D31, how='left', on='product_id')
D32.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,department_id,product_name,department,last,count,sum,reorder_rate
0,2539329,1,1,2,8,NaN,196,1,0,7,Soda,beverages,False,102,79,0.774510
1,2539329,1,1,2,8,NaN,14084,2,0,16,Organic Unsweetened Vanilla Almond Milk,dairy eggs,False,26,16,0.615385
2,2539329,1,1,2,8,NaN,12427,3,0,19,Original Beef Jerky,snacks,False,30,23,0.766667
3,2539329,1,1,2,8,NaN,26088,4,0,19,Aged White Cheddar Popcorn,snacks,False,6,1,0.166667
4,2539329,1,1,2,8,NaN,26405,5,0,17,XL Pick-A-Size Paper Towel Rolls,household,False,7,2,0.285714

In [121]:
D33 = D32[['order_dow', 'order_hour_of_day', 'days_since_prior_order', 'reorder_rate', 'reordered', 'last']].copy()
D33.head()

,order_dow,order_hour_of_day,days_since_prior_order,reorder_rate,reordered,last
0,2,8,NaN,0.774510,0,False
1,2,8,NaN,0.615385,0,False
2,2,8,NaN,0.766667,0,False
3,2,8,NaN,0.166667,0,False
4,2,8,NaN,0.285714,0,False

In [120]:
### days_since_prior_order 에 대한 처리 필요.. 
# D.fillna(D.mean)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,department_id,product_name,department,last
0,2539329,1,1,2,8,<bound method DataFrame.mean of order_i...,196,1,0,7,Soda,beverages,False
1,2539329,1,1,2,8,<bound method DataFrame.mean of order_i...,14084,2,0,16,Organic Unsweetened Vanilla Almond Milk,dairy eggs,False
2,2539329,1,1,2,8,<bound method DataFrame.mean of order_i...,12427,3,0,19,Original Beef Jerky,snacks,False
3,2539329,1,1,2,8,<bound method DataFrame.mean of order_i...,26088,4,0,19,Aged White Cheddar Popcorn,snacks,False
4,2539329,1,1,2,8,<bound method DataFrame.mean of order_i...,26405,5,0,17,XL Pick-A-Size Paper Towel Rolls,household,False
5,2398795,1,2,3,7,15,196,1,1,7,Soda,beverages,False
6,2398795,1,2,3,7,15,10258,2,0,19,Pistachios,snacks,False
7,2398795,1,2,3,7,15,12427,3,1,19,Original Beef Jerky,snacks,False
8,2398795,1,2,3,7,15,13176,4,0,4,Bag of Organic Bananas,produce,False
9,2398795,1,2,3,7,15,26088,5,1,19,Aged White Cheddar Popcorn,snacks,False
10,2398795,1,2,3,7,15,13032,6,0,14,Cinnamon Toast Crunch,breakfast,False
11,473747,1,3,3,12,21,196,1,1,7,Soda,beverages,False
12,473747,1,3,3,12,21,12427,2,1,19,Original Beef Jerky,snacks,False
13,473747,1,3,3,12,21,10258,3,1,19,Pistachios,snacks,False
14,473747,1,3,3,12,21,25133,4,0,16,Organic String Cheese,dairy eggs,False
15,473747,1,3,3,12,21,30450,5,0,13,Creamy Almond Butter,pantry,False
16,2254736,1,4,4,7,29,196,1,1,7,Soda,beverages,False
17,2254736,1,4,4,7,29,12427,2,1,19,Original Beef Jerky,snacks,False
18,2254736,1,4,4,7,29,10258,3,1,19,Pistachios,snacks,False
19,2254736,1,4,4,7,29,25133,4,1,16,Organic String Cheese,dairy eggs,False
20,2254736,1,4,4,7,29,26405,5,1,17,XL Pick-A-Size Paper Towel Rolls,household,False
21,431534,1,5,4,15,28,196,1,1,7,Soda,beverages,False
22,431534,1,5,4,15,28,12427,2,1,19,Original Beef Jerky,snacks,False
23,431534,1,5,4,15,28,10258,3,1,19,Pistachios,snacks,False
24,431534,1,5,4,15,28,25133,4,1,16,Organic String Cheese,dairy eggs,False
25,431534,1,5,4,15,28,10326,5,0,4,Organic Fuji Apples,produce,False
26,431534,1,5,4,15,28,17122,6,0,4,Honeycrisp Apples,produce,False
27,431534,1,5,4,15,28,41787,7,0,4,Bartlett Pears,produce,False
28,431534,1,5,4,15,28,13176,8,1,4,Bag of Organic Bananas,produce,False
29,3367565,1,6,2,7,19,196,1,1,7,Soda,beverages,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
77395,2591506,500,1,3,18,<bound method DataFrame.mean of order_i...,45194,9,0,16,Unsalted Sweet Cream Butter,dairy eggs,False
77396,2591506,500,1,3,18,<bound method DataFrame.mean of order_i...,9409,10,0,19,Dry Roasted Peanuts,snacks,False
77397,2591506,500,1,3,18,<bound method DataFrame.mean of order_i...,6029,11,0,11,Damage Therapy Intensive Repair Shampoo,personal care,False
77398,2591506,500,1,3,18,<bound method DataFrame.mean of order_i...,20540,12,0,11,Clinical Strength Secret Clinical Strength Smo...,personal care,False
77399,2591506,500,1,3,18,<bound method DataFrame.mean of order_i...,24735,13,0,1,Red Velvet Cake Ice Cream,frozen,False
77400,3305362,500,2,0,10,25,4674,1,0,7,Cherry Limeade,beverages,True
77401,3305362,500,2,0,10,25,28296,2,1,7,Lemon Lime Sparkling Water,beverages,True
77402,3305362,500,2,0,10,25,33852,3,1,7,Black Raspberry Sparkling Water Drink,beverages,True
77403,3305362,500,2,0,10,25,3526,4,0,7,Coconut Pineapple Sparkling Water,beverages,True
77404,3305362,500,2,0,10,25,41805,5,1,7,Strawberry Lemonade,beverages,True
77405,3305362,500,2,0,10,25,48071,6,0,4,Fresh Romaine Lettuce head,produce,True
77406,3305362,500,2,0,10,25,40354,7,0,4,California Clementines,produce,True
77407,3305362,500,2,0,10,25,18104,8,0,1,Favorites Alfredo Pasta with Chicken & Broccoli,frozen,True
77408,3305362,500,2,0,10,25,23819,9,0,4,Carrot,produce,True
77409,3305362,500,2,0,10,25,43772,10,0,4,Cherubs Heavenly Salad Tomatoes,produce,True
77410,3305362,500,2,0,10,25,34582,11,0,13,Natural Creamy Peanut Butter Spread,pantry,True
77411,3305362,500,2,0,10,25,1775,12,1,16,Caramel Macchiato Creamer,dairy eggs,True
77412,3305362,500,2,0,10,25,23276,13,1,19,Soup and Oyster Crackers,snacks,True
77413,3305362,500,2,0,10,25,37509,14,0,15,Light Chicken Noodle Soup,canned goods,True
77414,2546847,500,3,0,10,7,18104,1,1,1,Favorites Alfredo Pasta with Chicken & Broccoli,frozen,False
77415,2546847,500,3,0,10,7,40354,2,1,4,California Clementines,produce,False
77416,2546847,500,3,0,10,7,33852,3,1,7,Black Raspberry Sparkling Water Drink,beverages,False
77417,2546847,500,3,0,10,7,4674,4,1,7,Cherry Limeade,beverages,False
77418,2546847,500,3,0,10,7,28296,5,1,7,Lemon Lime Sparkling Water,beverages,False
77419,2546847,500,3,0,10,7,41805,6,1,7,Strawberry Lemonade,beverages,False
77420,2546847,500,3,0,10,7,48071,7,1,4,Fresh Romaine Lettuce head,produce,False
77421,2546847,500,3,0,10,7,27612,8,1,19,90 Calorie Lemon Bars,snacks,False
77422,2546847,500,3,0,10,7,43772,9,1,4,Cherubs Heavenly Salad Tomatoes,produce,False
77423,2546847,500,3,0,10,7,23819,10,1,4,Carrot,produce,False
77424,2546847,500,3,0,10,7,20919,11,0,4,Baby Spinach Salad,produce,False

In [122]:
from sklearn.impute import SimpleImputer

In [124]:
imp = SimpleImputer(strategy="mean")

In [142]:
from  sklearn.tree import DecisionTreeClassifier

In [143]:
# (Criterion: Gini, Splitter: Best, Max Depth:6, Seed: 13, Max Leaf Nodes: 25, 나머지 default) 
decision_clf = DecisionTreeClassifier(criterion="gini", splitter="best", max_depth=6, max_leaf_nodes=25, random_state=13)

In [129]:
from sklearn.pipeline import Pipeline

In [144]:
pipe = Pipeline([('imp', imp), ('reg', decision_clf)])

In [145]:
test_X = D33[D33['last']==True][['order_dow', 'order_hour_of_day', 'days_since_prior_order', 'reorder_rate']]
test_y = D33[D33['last']==True].reordered
train_X = D33[D33['last']==False][['order_dow', 'order_hour_of_day', 'days_since_prior_order', 'reorder_rate']]
train_y = D33[D33['last']==False].reordered

In [146]:
test_X.shape, test_y.shape, train_X.shape, train_y.shape

((4812, 4), (4812,), (72613, 4), (72613,))

In [147]:
pipe.fit(train_X, train_y)

Pipeline(memory=None,
     steps=[('imp', SimpleImputer(copy=True, fill_value=None, missing_values=nan, strategy='mean',
       verbose=0)), ('reg', DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=6,
            max_features=None, max_leaf_nodes=25,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=13,
            splitter='best'))])

In [149]:
predict = pipe.predict(test_X)

In [150]:
from sklearn.metrics import recall_score

In [151]:
recall_score(test_y, predict)

0.8708885616102111